### PR TITLE
Add colorscheme for ALE plugin

### PR DESCRIPTION
**Pull request by ok100**

### CODE REVIEW

**Comment by lfilho** [comment]
I did the sames locally and was about to issue this same PR. Ha!

But I would add two extra lines regarding `Info`. It's already present in ALE although not implemented yet. Care to add them, @ok100 ?

```vim
" ALE: {{{

call s:HL('ALEErrorLine', s:none, s:none, s:undercurl, s:red)
call s:HL('ALEWarningLine', s:none, s:none, s:undercurl, s:yellow)
call s:HL('ALEInfoLine', s:none, s:none, s:undercurl, s:blue)

hi! link ALEErrorSign GruvboxRedSign
hi! link ALEWarningSign GruvboxYellowSign
hi! link ALEInfoSign GruvboxBlueSign

" }}}
```

**Comment by lfilho** [comment]
@morhetz this PR supersedes #151

**Comment by lfilho** [comment]
ALE's author has just documented these highlights: https://github.com/w0rp/ale/commit/d5c9a4eb8719d733f2a4680f4f0e24128a9dad64

**Comment by lfilho** [comment]
@morhetz this is ~good~ great to go, @morhetz . Thank you very much!

**Comment by morhetz** [comment]
@lfilho 
That's all thanks to @ok100 
I'm just merging and reviewing that :)

@ok100 
Thanks a lot!

**Pull request merged**
